import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ClerkProvider } from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by NEXTjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <div className="flex flex-col  min-h-screen">
        <NavBar />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </div>

    </ClerkProvider>
  );
}
